steps: 123
place: "Palazzo della Civilt√† Italiana, Rome, Italy"
force: 0.5
noise: 0.01
sims: 2
size: 256
knn: 2

teams:
  blu:
    troop: 3
    armor: 3
    plane: 0
    civil: 0
    medic: 1
  red:
    troop: 3
    armor: 3
    plane: 0
    civil: 0
    medic: 0

rules:
  troop:
    health: 120
    damage: 15
    radius: 1
    speed: 2
    reach: 4
    sight: 4
    blast: 1
  armor:
    health: 120
    damage: 15
    radius: 1
    speed: 2
    reach: 4
    sight: 4
    blast: 1
  plane:
    health: 120
    damage: 15
    radius: 1
    speed: 2
    reach: 4
    sight: 4
    blast: 1
  civil:
    health: 120
    damage: 15
    radius: 1
    speed: 2
    reach: 4
    sight: 4
    blast: 1
  medic:
    health: 120
    damage: 15
    radius: 1
    speed: 2
    reach: 4
    sight: 4
    blast: 1
